<?php
namespace NooNoo;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-06-02 at 11:32:37.
 */
class ReplaceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Replace
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Replace;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers NooNoo\Replace::getPattern
     * @todo   Implement testGetPattern().
     */
    public function testGetPattern()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NooNoo\Replace::setPattern
     * @todo   Implement testSetPattern().
     */
    public function testSetPattern()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NooNoo\Replace::getReplacement
     * @todo   Implement testGetReplacement().
     */
    public function testGetReplacement()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NooNoo\Replace::setReplacement
     * @todo   Implement testSetReplacement().
     */
    public function testSetReplacement()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers NooNoo\Replace::replace
     * @todo   Implement testReplace().
     */
    public function testReplace()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
